### ISSUE TITLE
Develop full CLI Editor

### ISSUE THREAD

**Issue by jacob-macleod** [nathan-a-macleod/terminalEnv#1]
I'd like to develop a CLI editor with you(that you can use in this project). It can be programmed in a seperate github repo, and to run it, you would be able to do 'os.popen('python3 path/to/editor.py')' and 'quit()'. 
What do you think? Do you want to develop it with me?
I'd imagine it to be a professional, extensionable code editor, that runs the current saved file when youh hit a certain key conbination, and saves editor output to a text file before opening it with the text editor in a split window.

**Comment by nathan-a-macleod** [comment]
Right now, I am doing another version of the project in a separate branch, where when you open a program (like the software planner) in a separate window, instead of on a different screen. I am hoping that that branch will be ready to be merged into master in the next few days.

Once the branch has been merged to master, the new program would probably be best suited to the curses library, and the program could open in a new window. The program could be accessed in the main screen, and you can open it in a new window.

**EDIT**: I have now merged the stacking windows branch with master, and over the next few days, I am planning to do some small bug fixes, and polish it some more. Then, we can start to develop the fill CLI editor.

**Comment by jacob-macleod** [comment]
So can you open a program in a split view yet, or are you programming it now?
